---
title: Jesse Onolememen
timezone: UTC
collections:
  my_tags:
    title: My Tags
    output: true
    permalink: "/tag/:slug/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: my_tags
  values:
    layout: articles_by_tag
name: Jesse Onolememen
paginate: 25
paginate_path: "/posts/page/:num/"
url: 
blog_theme: dark
discus_identifier: 
ga_analytics: 
rss_enabled: true
social:
  dribbble: 
  facebook: 
  flickr: 
  github: jesster2k10
  linkedin: jesse-o-914a85122?trk=nav_responsive_tab_profile_pic
  twitter: jonolememen
  email: jesster2k10@gmail.com
  bitcoin: 1LFTEev8Mheg4pnDMdtMdcveKqTJvDeWYW
assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
  - _assets/bower
  - _assets/fonts
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
  - _vendor/
exclude:
- ".bowerrc"
- ".travis.yml"
- bin/*
- bower.json
- circle.yml
- Gemfile
- Gemfile.lock
- README.md
- vendor/
gems:
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
permalink: posts/:slug
